### ISSUE TITLE
Is there a getting start?

### ISSUE THREAD

**Issue by albertyou2** [simonwsw/cnn-zh#1]
HI@simonwsw 
Great work!
Recently I am very interesting in chinese  recognition , so I googled and found your repo.
But there is  no instructions in read me file .So I am wandering how to use your code .

Thank you very much!!!!

**Comment by simonwsw** [comment]
I'm sorry that currently there's no instructions of how to run the code in the readme. I'm thinking about adding some notes as you suggest. However I have no promise when it will be available.

**Comment by albertyou2** [comment]
OK ,I see .
Thank you !

**Comment by tengshaofeng** [comment]
@albertyou2 
hi, there are 3 models to run training such as lenet, logistic and mlp.
which one is the best? and which one  should  I chose?
Now, do you know the running sequence of the code  ?

**Comment by albertyou2** [comment]
@tengshaofeng 
I haven't use this project yet.I can't give your any suggestions,sorry~

**Comment by tengshaofeng** [comment]
@albertyou2 @simonwsw 
hi,all,
I rewrite the code in tensorflow and use the architecture as same as the paper said.
But it seams not converge. the code @simonwsw you provided is also not converged.
@albertyou2 then you reference which code?
